import type { Chapter, TreeHolon, NFT, PassportData, HotelData, ConversationSegment } from './types'

export const CHAPTERS: Chapter[] = [
  {
    number: 1,
    name: 'La Semilla',
    subtitle: 'The Seed',
    microseason: 'Dry season',
    months: 'November – February',
    narrative: 'Creation. The Maya made humans from corn — from a seed containing the entire future. You arrive as a seed: no history here yet. You register your first trees. Your name enters the forest permanently.',
    mayaElement: 'Yaxché — The World Tree',
    hook: 'Come back in the rainy season. Three of the trees you registered today will have flowered for the first time in years.',
    priceAdult: 85,
    priceChild: 45,
    available: true,
    locked: false,
    color: '#4A9B4A',
  },
  {
    number: 2,
    name: 'La Raíz',
    subtitle: 'The Root',
    microseason: 'Dry season end, first rains',
    months: 'March – May',
    narrative: 'Descent. The Maya underworld, Xibalba, was not punishment — it was transformation, accessed through roots and cenotes. You go deeper. You revisit your trees from Chapter 1 and observe what has changed.',
    mayaElement: 'Xibalba — The Underworld',
    hook: 'The rainy season transforms everything. Flowers you could not have seen in February will be open. Turtles will be nesting on the beach.',
    priceAdult: 85,
    priceChild: 45,
    available: false,
    locked: true,
    color: '#8B6914',
  },
  {
    number: 3,
    name: 'La Flor',
    subtitle: 'The Flower',
    microseason: 'Rainy season · peak biodiversity',
    months: 'June – August',
    narrative: 'Abundance. The rain god Chaac strikes the clouds. The forest explodes. Maximum species count, flowering trees, sea turtle nesting. Your job: document it precisely.',
    mayaElement: 'Chaac — The Rain God',
    hook: 'The storm season is coming. The forest knows. Come back and see what it does to prepare.',
    priceAdult: 85,
    priceChild: 45,
    available: false,
    locked: true,
    color: '#B85C8A',
  },
  {
    number: 4,
    name: 'La Tormenta',
    subtitle: 'The Storm',
    microseason: 'Hurricane season',
    months: 'September – October',
    narrative: 'Resilience. Not all chapters are easy. Your role this chapter is not to celebrate abundance but to witness and record stress: damaged trees, species displacement, recovery in progress.',
    mayaElement: 'Huracán — The Storm God',
    hook: 'The forest survived. It always does. Come back for Día de los Muertos — the Maya understood death differently.',
    priceAdult: 85,
    priceChild: 45,
    available: false,
    locked: true,
    color: '#5A5AA0',
  },
  {
    number: 5,
    name: 'El Retorno',
    subtitle: 'The Return',
    microseason: 'Post-storm transition',
    months: 'November (Hanal Pixán)',
    narrative: 'Ancestors. The festival Hanal Pixán honours the dead — but they are part of the living forest. You make a dedication: a tree sponsored in memory of someone. That dedication lives permanently.',
    mayaElement: 'Hanal Pixán — The Souls',
    hook: 'One chapter remains. The cycle completes at the winter solstice.',
    priceAdult: 85,
    priceChild: 45,
    available: false,
    locked: true,
    color: '#1A7A7A',
  },
  {
    number: 6,
    name: 'El Círculo',
    subtitle: 'The Circle',
    microseason: 'Winter solstice',
    months: 'December 21',
    narrative: 'Completion. At the solstice, the sun begins its return. You have walked Pulmón Verde across a full solar year. Chapter 6 is the ceremony: your passport is sealed, your contribution is certified.',
    mayaElement: 'K\'in — The Sun',
    hook: 'The cycle turns. New trees have grown. New animals have arrived. The forest changed while you were away.',
    priceAdult: 85,
    priceChild: 45,
    available: false,
    locked: true,
    color: '#C9A84C',
  },
]

export const MOCK_TREES: TreeHolon[] = [
  {
    id: 'tree-001',
    name: 'Tree #1',
    species: 'Manilkara zapota',
    commonName: 'Sapodilla',
    mayanName: "ya'",
    estimatedAge: 80,
    health: 'good',
    canopyRadius: 4.2,
    gpsLat: 20.6305,
    gpsLong: -87.0740,
    co2Annual: 0.42,
    threatLevel: 'low',
    observationCount: 3,
    firstRegistered: '2026-01-15',
    lastObserved: '2026-01-15',
    photo: '',
    latestObservation: '"A gecko has been seen in the hollow at the base for three years." — Rosa, Jan 15',
    registeredBy: 'James Miller',
  },
  {
    id: 'tree-002',
    name: 'Tree #2',
    species: 'Bursera simaruba',
    commonName: 'Gumbo Limbo',
    mayanName: 'chaka',
    estimatedAge: 45,
    health: 'good',
    canopyRadius: 3.1,
    gpsLat: 20.6308,
    gpsLong: -87.0737,
    co2Annual: 0.31,
    threatLevel: 'low',
    observationCount: 2,
    firstRegistered: '2026-01-15',
    lastObserved: '2026-01-15',
    registeredBy: 'James Miller',
  },
  {
    id: 'tree-003',
    name: 'Tree #3',
    species: 'Ceiba pentandra',
    commonName: 'Ceiba (World Tree)',
    mayanName: "Yaxché",
    estimatedAge: 200,
    health: 'good',
    canopyRadius: 8.5,
    gpsLat: 20.6312,
    gpsLong: -87.0733,
    co2Annual: 1.2,
    threatLevel: 'low',
    observationCount: 12,
    firstRegistered: '2026-01-15',
    lastObserved: '2026-01-15',
    latestObservation: '"Strong root buttresses, crown expanding. The most photographed tree in the forest." — Rosa',
    registeredBy: 'Mateo Miller (found first!)',
  },
  {
    id: 'tree-004',
    name: 'Tree #4',
    species: 'Cecropia obtusifolia',
    commonName: 'Guarumo',
    estimatedAge: 12,
    health: 'good',
    canopyRadius: 2.0,
    gpsLat: 20.6315,
    gpsLong: -87.0729,
    co2Annual: 0.28,
    threatLevel: 'low',
    observationCount: 1,
    firstRegistered: '2026-01-15',
    lastObserved: '2026-01-15',
    registeredBy: 'María Reyes',
  },
  {
    id: 'tree-005',
    name: 'Tree #5',
    species: 'Swietenia macrophylla',
    commonName: 'Mahogany',
    mayanName: 'chukum',
    estimatedAge: 60,
    health: 'fair',
    canopyRadius: 5.1,
    gpsLat: 20.6318,
    gpsLong: -87.0726,
    co2Annual: 0.55,
    threatLevel: 'medium',
    observationCount: 2,
    firstRegistered: '2026-01-15',
    lastObserved: '2026-01-15',
    latestObservation: '"Fungal growth on lower trunk. Monitoring closely." — Rosa',
    registeredBy: 'James Miller',
  },
]

export const MOCK_NFTS: NFT[] = [
  {
    id: 'nft-001',
    name: 'Sembrador — The Sower',
    chapter: 'Chapter 1 · La Semilla',
    rarity: 'common',
    soulbound: false,
    mintDate: '2026-01-15',
    imageEmoji: '🌱',
    description: 'Awarded for completing Chapter 1 — La Semilla. You have registered your first trees in the permanent forest record.',
  },
  {
    id: 'nft-002',
    name: 'Yaxché Witness',
    chapter: 'Chapter 1 · La Semilla',
    rarity: 'common',
    soulbound: false,
    mintDate: '2026-01-15',
    imageEmoji: '🌳',
    description: 'You visited the ceiba, the World Tree of Pulmón Verde. The Maya called it Yaxché — the axis connecting earth, sky, and underworld.',
  },
  {
    id: 'nft-003',
    name: 'Wildlife Witness — Zaphod',
    chapter: 'Chapter 1 · La Semilla',
    rarity: 'uncommon',
    soulbound: false,
    mintDate: '2026-01-15',
    imageEmoji: '🦎',
    description: 'You are the 23rd observer of Zaphod, the black iguana of Pulmón Verde. First recorded March 2024.',
  },
  {
    id: 'nft-004',
    name: 'Yaxché Finder',
    chapter: 'Chapter 1 · La Semilla',
    rarity: 'uncommon',
    soulbound: false,
    mintDate: '2026-01-15',
    imageEmoji: '🧭',
    description: 'Mateo Miller reached the ceiba first by compass, before any adult in the group. A natural navigator.',
  },
  {
    id: 'nft-005',
    name: 'Conservation Passport — Tier: Seed',
    chapter: 'Chapter 1 · La Semilla',
    rarity: 'rare',
    soulbound: true,
    mintDate: '2026-01-15',
    imageEmoji: '🛂',
    description: 'Your Conservation Passport. Valid at all Pulmón Verde affiliated sites. Upgrades with each chapter completed.',
  },
]

export const MOCK_PASSPORT: PassportData = {
  forestId: 'PV-0041',
  avatarId: 'avatar-james-miller',
  firstName: 'James',
  lastName: 'Miller',
  karma: 575,
  tier: 'seed',
  chaptersCompleted: 1,
  treesRegistered: 10,
  speciesDocumented: 4,
  volunteerHours: 2.3,
  co2Annual: 4.2,
  trees: MOCK_TREES,
  nfts: MOCK_NFTS,
  family: [
    { name: 'James Miller', type: 'adult', karma: 575, nftsEarned: 3, highlight: 'Registered 10 trees', emoji: '🌳' },
    { name: 'María Reyes', type: 'adult', karma: 575, nftsEarned: 3, highlight: 'Registered Trees #4, #7', emoji: '🌿' },
    { name: 'Sofía Miller', type: 'child', karma: 425, nftsEarned: 2, highlight: 'Spotted Zaphod the iguana', emoji: '🦎' },
    { name: 'Mateo Miller', type: 'child', karma: 450, nftsEarned: 2, highlight: 'Found the ceiba first by compass', emoji: '🧭' },
  ],
}

export const MOCK_TRANSCRIPT: ConversationSegment[] = [
  {
    time: '08:14',
    speaker: 'Rosa',
    speakerType: 'guide',
    treeName: 'Chicozapote · Tree #1',
    treeSpecies: 'Manilkara zapota',
    text: "This is a chicozapote — Manilkara zapota. The Maya called it ya'. The sap was used to make chicle — the original chewing gum, before Wrigley existed. This tree is approximately 80 years old.",
  },
  {
    time: '08:15',
    speaker: 'Sofía',
    speakerType: 'child',
    text: 'What lives in that hollow at the bottom?',
  },
  {
    time: '08:15',
    speaker: 'Rosa',
    speakerType: 'guide',
    text: "A gecko. I've seen him in exactly that spot for three years. He's as much a part of this tree as the bark.",
  },
  {
    time: '08:32',
    speaker: 'Rosa',
    speakerType: 'guide',
    treeName: 'Gumbo Limbo · Tree #2',
    treeSpecies: 'Bursera simaruba',
    text: 'We call this the tourist tree — look at the bark peeling, red underneath. The Maya used the resin as incense in ceremonies, and the sap to treat skin infections. It sunburns like us. That is why it is always peeling.',
  },
  {
    time: '09:02',
    speaker: 'Sofía',
    speakerType: 'child',
    treeName: 'Gumbo Limbo area',
    text: "There's an iguana! A big one!",
  },
  {
    time: '09:02',
    speaker: 'Rosa',
    speakerType: 'guide',
    text: "That is Zaphod. He was first registered in March 2024. You are his 23rd recorded observer. He lives in the gumbo limbo. He was here before we arrived and he will be here after we leave.",
  },
  {
    time: '09:34',
    speaker: 'Mateo',
    speakerType: 'child',
    treeName: 'Ceiba · Tree #3',
    text: "I found it! I found the big tree! My compass said north and I kept going north and here it is!",
  },
  {
    time: '09:34',
    speaker: 'Rosa',
    speakerType: 'guide',
    treeName: 'Ceiba · Tree #3',
    treeSpecies: 'Ceiba pentandra',
    text: "Mateo found it first. The Maya called this Yaxché — the Green Tree. It connects the sky, the earth, and the underworld. Everything in this forest grows around it. It is probably two hundred years old. Your great-great-great-grandparents were alive when this tree was a sapling.",
  },
  {
    time: '10:09',
    speaker: 'Rosa',
    speakerType: 'guide',
    treeName: 'Guarumo · Tree #10',
    treeSpecies: 'Cecropia obtusifolia',
    text: "This is one of the fastest-growing trees in the forest. In five years it will be twice this size. The hollow stems are home to a species of ant — Azteca — that protects the tree from other insects. They have a contract. The tree feeds the ants; the ants fight for the tree.",
  },
]

export const MOCK_HOTEL: HotelData = {
  name: 'Grand Hyatt Playa del Carmen',
  tier: 'partner',
  karma: 12840,
  rank: 3,
  totalHotels: 24,
  guestsThisMonth: 12,
  guestsDelta: 3,
  karmaThisMonth: 1200,
  treesSponsored: 4,
  co2Attributed: 2.1,
  guestActivity: [
    { date: 'Jan 15', guestName: 'J. Miller', chapter: 'Ch. 1', status: 'complete', karmaEarned: 575, optedInPublic: true },
    { date: 'Jan 13', guestName: 'A. Chen', chapter: 'Ch. 1', status: 'complete', karmaEarned: 490, optedInPublic: true },
    { date: 'Jan 11', guestName: 'M. Dupont', chapter: 'Ch. 1', status: 'in-progress', karmaEarned: 0, optedInPublic: false },
    { date: 'Jan 08', guestName: 'R. Santos', chapter: 'Ch. 1', status: 'complete', karmaEarned: 610, optedInPublic: true },
    { date: 'Jan 06', guestName: 'L. Park', chapter: 'Ch. 1', status: 'complete', karmaEarned: 520, optedInPublic: false },
    { date: 'Jan 04', guestName: 'P. Okafor', chapter: 'Ch. 1', status: 'complete', karmaEarned: 580, optedInPublic: true },
    { date: 'Dec 28', guestName: 'T. Nakamura', chapter: 'Ch. 1', status: 'complete', karmaEarned: 545, optedInPublic: true },
    { date: 'Dec 22', guestName: 'E. Rodrigues', chapter: 'Ch. 1', status: 'complete', karmaEarned: 600, optedInPublic: false },
  ],
  leaderboard: [
    { rank: 1, name: 'Thompson Beach House PDC', karma: 18450, guests: 87, trees: 12, co2: 6.2, isCurrentHotel: false },
    { rank: 2, name: 'Viceroy Riviera Maya', karma: 14200, guests: 62, trees: 8, co2: 3.9, isCurrentHotel: false },
    { rank: 3, name: 'Grand Hyatt Playa del Carmen', karma: 12840, guests: 54, trees: 4, co2: 2.1, isCurrentHotel: true },
    { rank: 4, name: 'Kore Tulum', karma: 11200, guests: 48, trees: 6, co2: 2.8, isCurrentHotel: false },
    { rank: 5, name: 'Xcaret Hotel', karma: 9800, guests: 41, trees: 3, co2: 1.4, isCurrentHotel: false },
    { rank: 6, name: 'Rosewood Mayakoba', karma: 8600, guests: 36, trees: 2, co2: 1.0, isCurrentHotel: false },
    { rank: 7, name: 'Banyan Tree Mayakoba', karma: 7400, guests: 31, trees: 2, co2: 0.9, isCurrentHotel: false },
    { rank: 8, name: 'Fairmont Mayakoba', karma: 6200, guests: 27, trees: 1, co2: 0.6, isCurrentHotel: false },
  ],
  notifications: [
    { id: '1', message: 'J. Miller (your guest) completed Chapter 1. Hotel earned 100 Karma.', time: '2h ago', type: 'karma' },
    { id: '2', message: "Your ceiba (Tree #12) was visited today. New health observation logged.", time: '5h ago', type: 'tree' },
    { id: '3', message: "You've moved to #3! Overtook Hotel Xcaret. 1,360 Karma from #2.", time: '1d ago', type: 'rank' },
    { id: '4', message: 'Your January impact report is ready to download.', time: '2d ago', type: 'report' },
  ],
}
